### ISSUE TITLE
Hosted example site failing

### ISSUE THREAD

**Issue by jaredtconnor** [Sentdex/socialsentiment#1]
FYI: The [SocialSentiment.net](SocialSentiment.net) link, which I'm assuming is the example site hosted on a live server, seems to be failing. A `Error loading dependencies` error is being raised. 

Browser: Version 64.0.3282.119 (Official Build) (32-bit)

**Comment by Sentdex** [comment]
Strange, looks fine to me and others. Try a refresh maybe? 

http://socialsentiment.net

**Comment by jaredtconnor** [comment]
Still seems to be getting the same issue, but I confirmed on a seperate machine that the site loads corretly. Sadly I imagine the issue is probably due to proxy issues. 

Closing out because the issue seem to be specific towards my network. 


![capture_2](https://user-images.githubusercontent.com/23062816/37435289-ed7ca850-279f-11e8-85d5-df514107a4ab.PNG)
