### ISSUE TITLE
no such module: fts5

### ISSUE THREAD

**Issue by rhnvrm** [Sentdex/socialsentiment#2]
`python twitter_stream.py` displays the following message and does not continue.

`no such module: fts5`

**Comment by munod** [comment]
I also have the same message
no such module: fts5

**Comment by daniel-kukiela** [comment]
Are you using Ubuntu (or Linux in general)?
Looks like your sqlite3 library is too old.

Possible fix for Ubuntu:
```
sudo add-apt-repository ppa:jonathonf/backports
sudo apt-get update && sudo apt-get install sqlite3
```

**Comment by doursand** [comment]
yes i am on ubuntu as well and I have the same error message
however if i go to sqlite3, it shows that fts5 is indeed activated

sqlite> pragma compile_options;
COMPILER=gcc-5.4.0 20160609
ENABLE_DBSTAT_VTAB
ENABLE_FTS4
ENABLE_FTS5
ENABLE_JSON1
ENABLE_RTREE
ENABLE_STMTVTAB
ENABLE_UNKNOWN_SQL_FUNCTION
HAVE_ISNAN
THREADSAFE=1

**Comment by doursand** [comment]
i am trying to follow this, will keep you posted
https://stackoverflow.com/questions/49053285/properly-install-sqlite3-with-fts5-support

**Comment by rhnvrm** [comment]
The solution of @daniel-kukiela works on DigitalOcean
